script: ./run-tests.sh

branches:
    only:
        - master

sudo: false

cache:
    directories:
        - $HOME/.local/lib/python2.7/site-packages/
        - $HOME/build/dlinknctu/OmniUI/ui/node_modules/
