var topologyData = {
  nodes: [{
    id: 0,
    controller: 'cs3',
    dpid: '00:00:00:1',
    nodeType: 'switch',
    tags: []
  }, {
    id: 1,
    controller: 'cs3',
    dpid: '00:00:00:2',
    nodeType: 'switch',
    tags: []
  }, {
    id: 2,
    controller: 'cs3',
    dpid: '00:00:00:3',
    nodeType: 'switch',
    tags: []
  }, {
    id: 3,
    controller: 'cs3',
    dpid: '00:00:00:4',
    nodeType: 'switch',
    tags: []
  }, {
    id: 4,
    controller: 'cs3',
    dpid: '00:00:00:5',
    nodeType: 'switch',
    tags: []
  }, {
    id: 5,
    controller: 'cs3',
    dpid: '00:00:00:6',
    nodeType: 'switch',
    tags: []
  }, {
    id: 6,
    controller: 'cs4',
    dpid: '00:00:00:7',
    nodeType: 'switch',
    tags: []
  }, {
    id: 7,
    controller: 'cs5',
    dpid: '00:00:00:8',
    nodeType: 'switch',
    tags: []
  }, {
    id: 8,
    controller: 'cs3',
    mac: 'ab:cd:ef:gh:aa',
    nodeType: 'host',
    tags: []
  }, {
    id: 9,
    controller: 'cs3',
    mac: 'ab:cd:ef:gh:bb',
    nodeType: 'host',
    tags: []
  }, {
    id: 10,
    controller: 'cs3',
    mac: 'ab:cd:ef:gh:cc',
    nodeType: 'host',
    tags: []
  }, {
    id: 11,
    controller: 'cs3',
    mac: 'ab:cd:ef:gh:dd',
    nodeType: 'host',
    tags: []
  }],
  links: [{
    id: 0,
    "source": 1,
    "target": 2
  }, {
    id: 1,
    "source": 1,
    "target": 3
  }, {
    id: 2,
    "source": 4,
    "target": 1
  }, {
    id: 3,
    "source": 2,
    "target": 3
  }, {
    id: 4,
    "source": 2,
    "target": 5
  }, {
    id: 5,
    "source": 3,
    "target": 6
  }, {
    id: 6,
    "source": 3,
    "target": 7
  }, {
    id: 7,
    "source": 3,
    "target": 8
  }],
  nodeSet: [{
    id: 8,
    type: 'nodeSet',
    nodes: [2, 3],
    root: '2',
    "name": "Node set 1",
    iconType: 'groupm'
  }, {
    id: 9,
    type: 'nodeSet',
    nodes: [1, 5],
    // root: '1',
    "name": "Node set 2",
    iconType: 'groupl'
  }]
}
